### ISSUE TITLE
Won't compile with protobuf 3.7.0

### ISSUE THREAD

**Issue by autrimpo** [rlite/rlite#85]
[config.log](https://github.com/rlite/rlite/files/2978350/config.log)

Trying to build the current master fails with the following error:

```
/home/autrimpo/src/rlite/user/uipcps/uipcp-normal-flow-alloc.cpp:32:8: error: cannot derive from 'final' base 'gpb::FlowRequest' in derived type 'rlite::FlowRequest'
 struct FlowRequest : public gpb::FlowRequest {
        ^~~~~~~~~~~
make[3]: *** [user/uipcps/CMakeFiles/uipcp-normal.dir/build.make:105: user/uipcps/CMakeFiles/uipcp-normal.dir/uipcp-normal-flow-alloc.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:1029: user/uipcps/CMakeFiles/uipcp-normal.dir/all] Error 2
make[1]: *** [Makefile:141: all] Error 2
make: *** [Makefile:8: usr] Error 2
```

I remember building rlite last month, after the latest commit, so I went and downgraded protobuf to 3.6.1. This solved the issue, but obviously isn't something desirable, as now my system is in an inconsistent state.

I'm going to look into the 3.7.0 changes to see what happened, but do you think there's a way we can support both in a nice maintainable way? Dropping pre-3.7.0 would break Debian et al., which is something we woudn't want, as many people pick those for their servers (e.g. I know the guys in Oslo run Debian on some of their machines, so this would prevent them from using rlite). On the other hand, I use a rolling distro (Void) and it's my understanding you develop on Arch, so it would be convenient to be able to continue without having to set up a VM or something similar just for rlite.

**Comment by autrimpo** [comment]
Related:
https://github.com/protocolbuffers/protobuf/issues/5869

**Comment by vmaffione** [comment]
Thanks for spotting this. The problem should be fixed now.

**Comment by autrimpo** [comment]
Thanks, works fine now.
